=== ManGilbert/AdvancedWebDesignDevelopment/xml/student/student.dtd
<!ELEMENT school (students, courses, enrollments)>

<!ELEMENT students (student+)>
<!ELEMENT student (name, email)>
<!ATTLIST student id ID #REQUIRED>

<!ELEMENT name (first, last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT courses (course+)>
<!ELEMENT course (title, instructor, credits)>
<!ATTLIST course id ID #REQUIRED>

<!ELEMENT title (#PCDATA)>
<!ELEMENT instructor (#PCDATA)>
<!ELEMENT credits (#PCDATA)>

<!ELEMENT enrollments (enrollment+)>
<!ELEMENT enrollment (grade)>
<!ATTLIST enrollment 
  studentID IDREF #REQUIRED 
  courseID IDREF #REQUIRED>

<!ELEMENT grade (#PCDATA)>

=== ManGilbert/AdvancedWebDesignDevelopment/xml/student/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE school SYSTEM "student.dtd">

<school>
  <students>
    <student id="202201">
        <name>
          <first>Beni</first>
          <last>Obed</last>
        </name>
        <email>beni.obed@gmail.com</email>
    </student>

    <student id="202202">
        <name>
          <first>Jean</first>
          <last>Paul</last>
        </name>
        <email>jean.paul@gmail.com</email>
      </student>
  </students>

  <courses>
    <course id="C101">
        <title>Intro to XML</title>
        <instructor>Solange</instructor>
        <credits>10</credits>
    </course>

    <course id="C202">
        <title>Database Systems</title>
        <instructor>Pierre</instructor>
        <credits>15</credits>
    </course>
  </courses>

  <enrollments>
    <enrollment studentID="202201" courseID="C101">
      <grade>A</grade>
    </enrollment>

    <enrollment studentID="202201" courseID="C202">
      <grade>B+</grade>
    </enrollment>

    <enrollment studentID="202202" courseID="C101">
      <grade>A-</grade>
    </enrollment>
  </enrollments>
</school>
